# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='passingGrade',
        ),
    ]
