# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20170301_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.Subject'),
            preserve_default=False,
        ),
    ]
