# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
