# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20170329_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='Description of the assignment'),
            preserve_default=False,
        ),
    ]
